let peraturan = "Peraturan Daerah Kota Semarang No. 4 Tahun 2016 Tentang Penyelenggaraan Administrasi Kependudukan";
let peraturanNikah = "Peraturan Daerah Kota Semarang No.9 1974 tentang perkawinan (Lembaga Negara Dalam Undang-Undang No. 32 Tahun 1954 tentang Pencatatan Nikah, Talak, dan Rujuk";
let Info = [
	{
		jenis_layanan : "Permohonan KK / KTP",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Kartu Keluarga",
			"Surat Keterangan Pindah Datang dari Daerah Asal",
			"FC Surat Nikah / Cerai",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di Isi oleh Pemohon",
			"Pemeriksaan Berkas",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Permohonan KTP Hilang",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Foto Copy KK",
			"Surat Keterangan Kehilangan Kepolisian",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di Isi oleh Pemohon",
			"Pemeriksaan Berkas",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Permohonan KK (Kartu Keluarga) Hilang",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Foto Copy KK",
			"Surat Keterangan Kehilangan Kepolisian",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di Isi oleh Pemohon",
			"Pemeriksaan Berkas",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Permohonan Pembuatan KTP",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Fc KK",
			"KTP",
			"Foto 3 x 4 berwarna",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Pembuatan Dokumen Kelahiran",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Fc KK dan E-KTP",
			"Surat Nikah Orang Tua",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Pembuatan Dokumen Kematian",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Fc KK dan E-KTP",
			"Surat Nikah Orang Tua (jika sudah menikah)",
			"Surat Keterangan Kematian",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Keterangan Jaminan Bertempat Tinggal",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Fc E-KTP",
			"Surat Keterangan Boro Daerah Asal",
			"Foto 3 x 4 Berawarna",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar, Surat Keterangan",
	},
	{
		jenis_layanan : "Pengantar Pindah",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Foto 3 x 4 Berawarna",
			"Fc E-KTP",
			"Kartu Keluarga (KK)",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar, Surat Keterangan",
	},
	{
		jenis_layanan : "Pengantar Pindah Datang",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Foto 3 x 4 Berawarna",
			"Surat Keterangan Pindah dari Tempat Asal",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar, Surat Keterangan",
	},
	{
		jenis_layanan : "Keterangan Domisili",
		dasar_hukum : peraturan,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Foto 3 x 4 Berawarna",
			"Fc Akta Pendirian Badan Hukum di hadapan Notaris",
			"Survei Permohonan",
			"Surat Keterangan Penduduk Permanen (domisili)",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Keterangan Untuk Nikah",
		dasar_hukum : peraturanNikah,
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Fc E-KTP",
			"Fc KK",
			"Fc Surat Nikah Orang Tua",
			"Fc Akta Kelahiran",
			"Fc Ijazah Terakhir",
			"Surat Pernyataan Belum Menikah",
			"Akte Cerai Janda / Duda",
			"Akte Kematian Bagi Janda / Duda",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Keterangan untuk Nikah (N1/N4)",
	},
	{
		jenis_layanan : "Keterangan Ahli Waris",
		dasar_hukum : "Peraturan Pemerintah No 10 Tahun 1961 Tentang Pendaftaran Tanah",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Surat Kematian",
			"Surat Pernyataan Waris",
			"FC KK",
			"FC E-KTP",
			"Akta Kelahiran Bagi Ahli Waris di bawah umur",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan (bila perlu)",
			"Penerbitan Dokumen (ahli waris harus hadir)",
			"Penyerahan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Surat Keterangan Warisan",
	},
	{
		jenis_layanan : "Keterangan Tidak Sengketa",
		dasar_hukum : "Peraturan Pemerintah No 24 Tahun 1997 Tentang Pendaftaran Tanah",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"FC Bukti Kepemilikan Tanah (dengan menunjukkan aslinya)",
			"Surat Pernyataan Tidak sengketa (diketahui 2 orang saksi / Ketua RT dan RW)",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penyerahan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Penguasaan Atas Tanah Negara",
		dasar_hukum : "Peraturan Pemerintah No 10 Tahun 1961 Tentang Pendaftaran Tanah",
		persyaratan : [
			"FC E-KTP",
			"Bukti Penguasaan Tanah",
			"FC PBB Tahun Terakhir",
			"Surat Permohonan",
			"Surat Pernyataan Bermaterai",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Pelimpahan Tanah Negara Tanah Garapan",
		dasar_hukum : "Peraturan Pemerintah No 10 Tahun 1961 Tentang Pendaftaran Tanah",
		persyaratan : [
			"FC E-KTP",
			"Bukti Penguasaan Tanah",
			"FC PBB Tahun Terakhir",
			"Surat Permohonan",
			"Surat Pernyataan Bermaterai",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Surat Keterangan Tidak Mampu",
		dasar_hukum : "Peraturan Presiden No 166 tahun 2014 tentang Penanggulangan Kemiskinan",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"Fc KK",
			"Kartu Identitas Miskin (KIM) Formulir Verifikasi Warga Miskin",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan (Bila Perlu)",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Surat Keterangan",
	},
	{
		jenis_layanan : "Persetujuan Pendirian Lembaga Pendidikan",
		dasar_hukum : "Peraturan Daerah Kota Semarang No. 1 tahun 2007 tentang Penyelenggaraan Pendidikan di Kota Semarang",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Proposal Pendirian Lembaga Pendidikan",
			"Akta Pendirian Yayasan dibuat di hadapan Notaris dan disahkan Kemenkuham",
			"Fc E-KTP Ketua Yayasan",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan (Bila Perlu)",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Formulir Persetujuan Pendidikan Lembaga Pendidikan",
	},
	{
		jenis_layanan : "Surat Keterangan Catatan Kepolisian (SKCK)",
		dasar_hukum : "Peraturan Kapolri No 18 tahun 2014 tentang tata cara Penerbitan Surat Keterangan Catatan Kepolisian",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC KK",
			"FC KTP",
			"FC Akta Kelahiran",
			"Foto ukuran 4x6 berwarna",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Rekomendasi Keramaian",
		dasar_hukum : "Petunjuk Lapangan No Polisi Juklap / 02 / XII / 1995 tentang Perijinan dan Pemberitahuan Kegiatan Masyarakat",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Persetujuan Mendirikan Bantuan",
		dasar_hukum : "Perda Kota Semarang No. 5 tahun 2009 tentang Bangunan Gedung",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"FC Keterangan Rencana Kota (KRK) dengan menunjukkan aslinya",
			"Bukti Kepemilikan tanah",
			"Bukti Lunas PBB",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan (Bila Perlu)",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Formulir Ijin Mendirikan Bangunan",
	},
	{
		jenis_layanan : "Persetujuan Bantuan Pembangunan Sarana / Prasarana Umum",
		dasar_hukum : "Permendagri No. 39 tahun 2012 tentang Perubahan atas Permendagri No 32 tahun 2011 tentang Pedoman Pemberian Hibah dan Bantuan Sosial yang bersumber dari APBD",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"Surat Permohonan dan Proposal",
			"FC Akta Pendirian Badan Hukum yang disahkan oleh Kemenhumkan dan HAM",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penerbitan Dokumen",
			"Penyerahan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Persetujuan Proposal",
	},
	{
		jenis_layanan : "Persetujuan Pembangunan Sarana Sosial",
		dasar_hukum : "Permendagri No. 39 tahun 2012 tentang Perubahan atas Permendagri No 32 tahun 2011 tentang Pedoman Pemberian Hibah dan Bantuan Sosial yang bersumber dari APBD",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"Surat Permohonan dan Proposal",
			"FC Akta Pendirian Badan Hukum yang disahkan oleh Kemenhumkan dan HAM",
			"FC E-KTP",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Persetujuan Proposal",
	},
	{
		jenis_layanan : "Persetujuan Lain HO",
		dasar_hukum : "Peraturan Daerah Kodya Dati II Semarang tentang Retiribusi Ijin Gangguan",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"FC Bukti Kepemilikan Tanah",
			"FC Bukti Pelunasan PBB Tahun Berjalan",
			"FC Akta Pendirian Badan Hukum yang disahkan oleh Pejabat Berwenang",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Berita Acara Persetujuan Warga",
	},
	{
		jenis_layanan : "Persetujuan Penyambungan Jalan Masuk",
		dasar_hukum : "Peraturan Daerah Kota Semarang No 22 tahun 2011 tentang Penyambungan Jalan Masuk",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"FC Bukti Kepemilikan Tanah",
			"Denah Lokasi",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
			"Penerbitan Dokumen",
		],
		jangka_waktu : "3 Jam",
		produk_pelayanan : "Surat Pengantar",
	},
	{
		jenis_layanan : "Permohonan Pembuatan Ijin Usaha Mikro dan Kecil (UMKM)",
		dasar_hukum : "Peraturan Daerah Kota Semarang No 4 tahun 2016 tentang Penyelenggaraan Administrasi Kependudukan",
		persyaratan : [
			"Surat Pengantar RT / RW",
			"FC E-KTP",
			"FC KK",
			"Foto 3x4 Berwarna",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
		],
		jangka_waktu : "15 Menit",
		produk_pelayanan : "Formulir Persetujuan Penyambungan Jalan Masuk",
	},
	{
		jenis_layanan : "Persetujuan / Pendirian Penempatan Menara Telekomunikasi",
		dasar_hukum : "Keputusan Menteri No. 93 tahun 2014 tentang Rencana Induk Bandar Udara Ahmad Yani Semarang Jawa Tengah. Peraturan Walikota Semarang No. 8 Tahun 2007 tentang tata cara Penyelenggaraan penataan Menara Telekomunikasi bersama Kota Semarang",
		persyaratan : [
			"Persetujuan Ijin Warga dalam radius disetujui / diketahui Ketua RT/RW",
			"Gambar radius rebahan menara disetujui / diketahui Ketua RT / RW",
			"FC E-KTP",
			"Surat Permohonan",
			"Bentuk Gambar Menara",
			"FC Bukti Kepemilikan Tanah",
		],
		sistem_mekanisme : [
			"Pendaftaran",
			"Penyerahan Berkas yang Telah Di isi oleh Pemohon",
			"Pemeriksaan Berkas Dokuman",
			"Peninjauan Lapangan",
		],
		jangka_waktu : "3 jam",
		produk_pelayanan : "Surat Persetujuan Lingkungan / Berita Acara",
	},
]

export default Info;